required = ["github.com/golang/mock/mockgen"]

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[[constraint]]
  name = "github.com/Clever/kayvee-go"
  version = "6.10.0"

[[constraint]]
  name = "github.com/google/go-github"
  branch = "master"

[[constraint]]
  name = "github.com/knq/jwt"
  branch = "master"

[[constraint]]
  name = "github.com/knq/pemutil"
  branch = "master"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "^0.5.0"

[[override]]
  name = "github.com/Clever/who-is-who"
  branch = "master"
