// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/NathanLeiby/go/src/github.com/Clever/pickabot/who_is_who_client_iface.go

package main

import (
	go_client "github.com/Clever/who-is-who/go-client"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockwhoIsWhoClientIface is a mock of whoIsWhoClientIface interface
type MockwhoIsWhoClientIface struct {
	ctrl     *gomock.Controller
	recorder *MockwhoIsWhoClientIfaceMockRecorder
}

// MockwhoIsWhoClientIfaceMockRecorder is the mock recorder for MockwhoIsWhoClientIface
type MockwhoIsWhoClientIfaceMockRecorder struct {
	mock *MockwhoIsWhoClientIface
}

// NewMockwhoIsWhoClientIface creates a new mock instance
func NewMockwhoIsWhoClientIface(ctrl *gomock.Controller) *MockwhoIsWhoClientIface {
	mock := &MockwhoIsWhoClientIface{ctrl: ctrl}
	mock.recorder = &MockwhoIsWhoClientIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockwhoIsWhoClientIface) EXPECT() *MockwhoIsWhoClientIfaceMockRecorder {
	return _m.recorder
}

// UserBySlackID mocks base method
func (_m *MockwhoIsWhoClientIface) UserBySlackID(_param0 string) (go_client.User, error) {
	ret := _m.ctrl.Call(_m, "UserBySlackID", _param0)
	ret0, _ := ret[0].(go_client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserBySlackID indicates an expected call of UserBySlackID
func (_mr *MockwhoIsWhoClientIfaceMockRecorder) UserBySlackID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UserBySlackID", reflect.TypeOf((*MockwhoIsWhoClientIface)(nil).UserBySlackID), arg0)
}

// UpsertUser mocks base method
func (_m *MockwhoIsWhoClientIface) UpsertUser(_param0 string, _param1 go_client.User) (go_client.User, error) {
	ret := _m.ctrl.Call(_m, "UpsertUser", _param0, _param1)
	ret0, _ := ret[0].(go_client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser
func (_mr *MockwhoIsWhoClientIfaceMockRecorder) UpsertUser(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UpsertUser", reflect.TypeOf((*MockwhoIsWhoClientIface)(nil).UpsertUser), arg0, arg1)
}

// GetUserList mocks base method
func (_m *MockwhoIsWhoClientIface) GetUserList() ([]go_client.User, error) {
	ret := _m.ctrl.Call(_m, "GetUserList")
	ret0, _ := ret[0].([]go_client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserList indicates an expected call of GetUserList
func (_mr *MockwhoIsWhoClientIfaceMockRecorder) GetUserList() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetUserList", reflect.TypeOf((*MockwhoIsWhoClientIface)(nil).GetUserList))
}
