// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/briannaveenstra/go/src/github.com/Clever/pickabot/who_is_who_client_iface.go

// Package main is a generated GoMock package.
package main

import (
	go_client "github.com/Clever/who-is-who/go-client"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockwhoIsWhoClientIface is a mock of whoIsWhoClientIface interface
type MockwhoIsWhoClientIface struct {
	ctrl     *gomock.Controller
	recorder *MockwhoIsWhoClientIfaceMockRecorder
}

// MockwhoIsWhoClientIfaceMockRecorder is the mock recorder for MockwhoIsWhoClientIface
type MockwhoIsWhoClientIfaceMockRecorder struct {
	mock *MockwhoIsWhoClientIface
}

// NewMockwhoIsWhoClientIface creates a new mock instance
func NewMockwhoIsWhoClientIface(ctrl *gomock.Controller) *MockwhoIsWhoClientIface {
	mock := &MockwhoIsWhoClientIface{ctrl: ctrl}
	mock.recorder = &MockwhoIsWhoClientIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockwhoIsWhoClientIface) EXPECT() *MockwhoIsWhoClientIfaceMockRecorder {
	return m.recorder
}

// UserBySlackID mocks base method
func (m *MockwhoIsWhoClientIface) UserBySlackID(arg0 string) (go_client.User, error) {
	ret := m.ctrl.Call(m, "UserBySlackID", arg0)
	ret0, _ := ret[0].(go_client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserBySlackID indicates an expected call of UserBySlackID
func (mr *MockwhoIsWhoClientIfaceMockRecorder) UserBySlackID(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserBySlackID", reflect.TypeOf((*MockwhoIsWhoClientIface)(nil).UserBySlackID), arg0)
}

// UpsertUser mocks base method
func (m *MockwhoIsWhoClientIface) UpsertUser(arg0 string, arg1 go_client.User) (go_client.User, error) {
	ret := m.ctrl.Call(m, "UpsertUser", arg0, arg1)
	ret0, _ := ret[0].(go_client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser
func (mr *MockwhoIsWhoClientIfaceMockRecorder) UpsertUser(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockwhoIsWhoClientIface)(nil).UpsertUser), arg0, arg1)
}

// GetUserList mocks base method
func (m *MockwhoIsWhoClientIface) GetUserList() ([]go_client.User, error) {
	ret := m.ctrl.Call(m, "GetUserList")
	ret0, _ := ret[0].([]go_client.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserList indicates an expected call of GetUserList
func (mr *MockwhoIsWhoClientIfaceMockRecorder) GetUserList() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserList", reflect.TypeOf((*MockwhoIsWhoClientIface)(nil).GetUserList))
}
