// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Clever/pickabot/slackapi (interfaces: SlackAPIService,SlackRTMService)

// Package mock_slackapi is a generated GoMock package.
package mock_slackapi

import (
	gomock "github.com/golang/mock/gomock"
	slack "github.com/nlopes/slack"
	reflect "reflect"
)

// MockSlackAPIService is a mock of SlackAPIService interface
type MockSlackAPIService struct {
	ctrl     *gomock.Controller
	recorder *MockSlackAPIServiceMockRecorder
}

// MockSlackAPIServiceMockRecorder is the mock recorder for MockSlackAPIService
type MockSlackAPIServiceMockRecorder struct {
	mock *MockSlackAPIService
}

// NewMockSlackAPIService creates a new mock instance
func NewMockSlackAPIService(ctrl *gomock.Controller) *MockSlackAPIService {
	mock := &MockSlackAPIService{ctrl: ctrl}
	mock.recorder = &MockSlackAPIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSlackAPIService) EXPECT() *MockSlackAPIServiceMockRecorder {
	return m.recorder
}

// GetChannelInfo mocks base method
func (m *MockSlackAPIService) GetChannelInfo(arg0 string) (*slack.Channel, error) {
	ret := m.ctrl.Call(m, "GetChannelInfo", arg0)
	ret0, _ := ret[0].(*slack.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelInfo indicates an expected call of GetChannelInfo
func (mr *MockSlackAPIServiceMockRecorder) GetChannelInfo(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelInfo", reflect.TypeOf((*MockSlackAPIService)(nil).GetChannelInfo), arg0)
}

// GetUserInfo mocks base method
func (m *MockSlackAPIService) GetUserInfo(arg0 string) (*slack.User, error) {
	ret := m.ctrl.Call(m, "GetUserInfo", arg0)
	ret0, _ := ret[0].(*slack.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo
func (mr *MockSlackAPIServiceMockRecorder) GetUserInfo(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockSlackAPIService)(nil).GetUserInfo), arg0)
}

// NewRTM mocks base method
func (m *MockSlackAPIService) NewRTM() *slack.RTM {
	ret := m.ctrl.Call(m, "NewRTM")
	ret0, _ := ret[0].(*slack.RTM)
	return ret0
}

// NewRTM indicates an expected call of NewRTM
func (mr *MockSlackAPIServiceMockRecorder) NewRTM() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRTM", reflect.TypeOf((*MockSlackAPIService)(nil).NewRTM))
}

// MockSlackRTMService is a mock of SlackRTMService interface
type MockSlackRTMService struct {
	ctrl     *gomock.Controller
	recorder *MockSlackRTMServiceMockRecorder
}

// MockSlackRTMServiceMockRecorder is the mock recorder for MockSlackRTMService
type MockSlackRTMServiceMockRecorder struct {
	mock *MockSlackRTMService
}

// NewMockSlackRTMService creates a new mock instance
func NewMockSlackRTMService(ctrl *gomock.Controller) *MockSlackRTMService {
	mock := &MockSlackRTMService{ctrl: ctrl}
	mock.recorder = &MockSlackRTMServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSlackRTMService) EXPECT() *MockSlackRTMServiceMockRecorder {
	return m.recorder
}

// NewOutgoingMessage mocks base method
func (m *MockSlackRTMService) NewOutgoingMessage(arg0, arg1 string) *slack.OutgoingMessage {
	ret := m.ctrl.Call(m, "NewOutgoingMessage", arg0, arg1)
	ret0, _ := ret[0].(*slack.OutgoingMessage)
	return ret0
}

// NewOutgoingMessage indicates an expected call of NewOutgoingMessage
func (mr *MockSlackRTMServiceMockRecorder) NewOutgoingMessage(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOutgoingMessage", reflect.TypeOf((*MockSlackRTMService)(nil).NewOutgoingMessage), arg0, arg1)
}

// SendMessage mocks base method
func (m *MockSlackRTMService) SendMessage(arg0 *slack.OutgoingMessage) {
	m.ctrl.Call(m, "SendMessage", arg0)
}

// SendMessage indicates an expected call of SendMessage
func (mr *MockSlackRTMServiceMockRecorder) SendMessage(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockSlackRTMService)(nil).SendMessage), arg0)
}
